version: 1.0
app:
  instances:
    min: 1
    max: 3
  resources:
    cpu: 1
  env:
    - name: MY_ENV
      value: "1"
    - name: sslconn
      value: "false"
  variables:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  version: ""
  java: 21
  endpoints: public
