version: 1.0
app:
  instances:
    min: 1
    max: 3
  resources:
    cpu: 1
  env:
    - name: MY_ENV
      value: "1"
    - name: sslconn
      value: "false"
  variables:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
  version: "a2adef23-d23f-4cfc-8811-224f9550b7d8"
  java: 17
  endpoints: public
